name: gym_progress_tracker
description: A cross-platform fitness app to log workouts and track progress.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  firebase_core: ^2.6.0
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.4.5
  google_sign_in: ^6.1.0
  provider: ^6.0.5
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  flutter_facebook_auth: ^6.0.4
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true 